### PR TITLE
airmon-ng: do not replace perfectly fine driver name with ?????

### PR DESCRIPTION
**Pull request by rofl0r**

### CODE REVIEW

**Comment by rofl0r** [comment]
background: when modinfo is available, MODINFO=1 will be set, but it later will not produce any result when the driver is statically built into the kernel. so the driver name that was previously extracted from sysfs gets overwritten with ????? again.

**Comment by ZeroChaos-** [comment]
great, thanks! committed in svn

**Comment by rofl0r** [comment]
thanks!

**Comment by rofl0r** [comment]
ftr: merged as https://github.com/aircrack-ng/aircrack-ng/commit/43245ef2e41c97c3cbb50397a36c758a9f795361

**Pull request closed without merging**
