### PR TITLE
Fix -Wimplicit fallthrough found when build with gcc7

### PR DESCRIPTION
**Pull request by alagoutte**

### CODE REVIEW

**Comment by aircrack-ng** [comment]
They're all correct, except airdecloak-ng ones where the fallthrough is purposeful.

Update and use ```__attribute__ ((fallthrough));``` for airdecloak-ng.

**Comment by alagoutte** [comment]
for both case ?

**Comment by aircrack-ng** [comment]
yes.

**Comment by aircrack-ng** [comment]
Committed in [r3038](https://trac.aircrack-ng.org/changeset/3038).

**Pull request closed without merging**
