### PR TITLE
There is a better way to delete a node from a list

### PR DESCRIPTION
**Pull request by lidonghai**
Learned from linus's speach on TED, it's a better way to do the same thing

### CODE REVIEW

**Comment by Mister-X-** [comment]
Do you have a link to that speech?

**Comment by lidonghai** [comment]
actually it should be an interview :P
I watched that on a Chinese site, but i think the original url is http://www.ted.com/talks/linus_torvalds_the_mind_behind_linux

**Comment by Mister-X-** [comment]
Tested and it's good.

When I think about it, the ```prev``` pointer is present in the structure and used at a few places. Which makes me wonder if there is a reason why it hasn't been set in this function.

**Comment by lidonghai** [comment]
aha, may be it is a bug, `prev` of  struct `NA_info` only used once in the whole `airodump-ng.c` file. 
I just modified this function according to it's previous version, so it was my neglect :(
I will cancel this pull, and repull a new one. Thanks for your reminder

**Comment by Mister-X-** [comment]
You didn't neglect anything, you improved the code. What I mentioned was merely a reminder for me to look at it and fix it.

**Comment by lidonghai** [comment]
I searched the source code, but I have no idea about the necessary of `prev`,  for performance?
personally, I think all the `prev` does can be instead by `next` in this project, I din't find any special use of it,can u enlighten me ?

**Pull request closed without merging**
