### PR TITLE
airodump-ng: added option to ignore specified BSSIDs

### PR DESCRIPTION
**Pull request by hanswolff**
I added an option to enable capturing all stations except certain BSSIDs. It was tested on a Raspberry Pi and it works like charm.

### CODE REVIEW

**Comment by aircrack-ng** [comment]
Will be added after 1.2 final.

**Comment by dmackey0** [comment]
@aircrack-ng I would love to see @hanswolff 's regex based filtering incorporated into aircrack-ng proper.

**Comment by sethleedy** [comment]
Great! Needing that option!

**Comment by sa7mon** [comment]
Would it be possible to also add this functionality to besside-ng? It would be incredibly useful.

**Comment by RealEnder** [comment]
@sa7mon You can always add fake entry in besside.log for the net/s you want not to be attacked.

**Comment by mabed-fr** [comment]
@aircrack-ng  @sethleedy 
Cela a t'il été ajouté ? comment l'utilisé ? 

It has you he added? How the used?

**Pull request closed without merging**
