### PR TITLE
Channel 165 missing from header file

### PR DESCRIPTION
**Pull request by skmpz**
Channel 165 missing in header file so we can't capture packets on it.

### CODE REVIEW

**Comment by ZeroChaos-** [comment]
ACK
Also of note, "-C0" tests all frequencies and captures on the successful ones :-)

**Comment by Mister-X-** [comment]
More channels need to be added: https://en.wikipedia.org/wiki/List_of_WLAN_channels#5.C2.A0GHz_.28802.11a.2Fh.2Fj.2Fn.2Fac.29.5B17.5D

I need to also check in osdep channel to frequency conversion code.

**Comment by Cnly** [comment]
Hi, I am also coming into this problem and am wondering when can these channels be added. The times of 5GHz has come and I think aircrack-ng should also keep up the great work and adapt it. :)

**Comment by kimocoder** [comment]
Yes, lots of channels needs to be added besides this commit there are lots of others too.

**Comment by aircrack-ng** [comment]
Superseded by [r2926](http://trac.aircrack-ng.org/changeset/2926). By the way, those were the hopping channels in airodump-ng. If I'm correct, it didn't prevent setting the channel to something different from what was in the hopping pattern.

**Pull request closed without merging**
