### PR TITLE
airodump-ng: Support to show a WPS column with WPS version, config method(s) and AP setup locked, for APs with WPS enabled.

### PR DESCRIPTION
**Pull request by yh0-**
I made some changes based on https://github.com/aircrack-ng/aircrack-ng/pull/11 and iw print_wifi_wps. Please review.

### CODE REVIEW

**Comment by clopez** [comment]
I have tested it, looks good. I think we can merge it.

@Mister-X- I have documented at http://trac.aircrack-ng.org/wiki/GitHub how to merge GitHub patches, with a focus on giving proper credit to the authors.

In this case the credit for the patch should be given both to the author of the original implementation (@darkosancanin at #11) and to @yh0- for the improved version.

@Mister-X- I can merge it myself if you think the implementation is OK

**Comment by Mister-X-** [comment]
Go ahead.

**Comment by Mister-X-** [comment]
@clopez, do you plan on committing it or should I?

**Comment by clopez** [comment]
I tried to do it the other day, unfortunately the patch not longer applies :(.

I tried to rebase it on top of current trunk, but it took me more time than expected and I wasn't able to finish it on time. Lately I'm a bit busy with other things so I don't think I will have time (at least) on the coming weeks to retake this.

So if you can do it, that would be great.

Otherwise, if @yh0- can submit an updated/rebased patch on top of current master/trunk, that would help.

Regards.

**Comment by yh0-** [comment]
@clopez & @Mister-X-, I have prepared the patch for the current trunk. Feel free to review.

Best regards.

**Comment by clopez** [comment]
@Mister-X- I think it will be better if we can change the short option for "--write-interval" from the actual "-W" to "-I", that way we can use "-W" for this new feature "--wps". IMHO is more consistent. Otherwise we would have to use '-z' (as @yh0- used on his last version of the patch) or use '-P'. None of the two seems ideal.
Since we still haven't released any version of aircrack with the --write-interval feature, I think we are still on time to do that.

@Mister-X- Do you agree on using "-I" for "--write-interval"?

**Comment by ZeroChaos-** [comment]
+1 on -I

**Comment by Mister-X-** [comment]
OK for the parameter change but that change must be a separate commit (don't forget the man page).

**Comment by clopez** [comment]
I have changed the param for wps-interval in http://trac.aircrack-ng.org/changeset/2504 and I have committed the WPS feature in http://trac.aircrack-ng.org/changeset/2505.

@yh0- In this pull request there are a couple of unrelated patches to this feature. Please split the other features and submit new pull requests for them. Please, use one pull request per feature, don't submit unrelated features or patches to a given pull request.

I'm closing this pull request, @yh0- please clean the other patches and submit new pull request for them.

Thanks for the patch.

**Pull request closed without merging**
