### PR TITLE
Update common.mak

### PR DESCRIPTION
**Pull request by johschmitz**

### CODE REVIEW

**Comment by aircrack-ng** [comment]
Could you give me some details about what your patch do?

**Comment by johschmitz** [comment]
Without this I couldn't compile.
This was on a Ubuntu 13.04 system.
I was getting this error:
common.mak:88: **\* commands commence before first target.  Stop.

**Comment by aircrack-ng** [comment]
Well, the patch is not correct. What if you replace the Y in your patch by 2 single quotes (or 2 double quotes). Does it work?

**Comment by pensierinmusica** [comment]
+1

I get the same error on Debian when trying to compile: `commands commence before first target`.

**Comment by johschmitz** [comment]
Quotes seem to be working fine.

**Comment by aircrack-ng** [comment]
Fix committed in r2402. Does it work for both of you?

**Comment by pensierinmusica** [comment]
It still gives me some errors when trying to compile... Here's a screenshot:
screenshot

**Comment by aircrack-ng** [comment]
Please make sure you install all the dependencies as explained in the documentation.

**Comment by pensierinmusica** [comment]
Hi, it's all working now... thanks! The git repo readme doesn't mention that `pkg-config` is required to do the install, this bit of information is only written on the `aircrack-ng` website. Should I fix it and make a pull request? Cheers!

**Comment by aircrack-ng** [comment]
Committed to r2403.

**Pull request closed without merging**
